version: '3.3'

volumes:
  pg_data:
  static:
  media:
  redoc:

services:
  db:
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - redoc:/app/docs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /static/
    volumes:
      - ./frontend/:/app/result_build/

  gateway:
    build: ./infra/
    image: nginx:1.19.3
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - static:/var/html/static
      - media:/var/html/media
      - redoc:/usr/share/nginx/html/api/docs/
