version: '3.3'

volumes:
  pg_data_foodgram:
  foodgram_static:
  foodgram_media:

services:
  db:
    image: postgres:13.10-alpine
    env_file: ../.env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data

  backend:
    image: julianastr/foodgram_backend
    env_file: ../.env
    restart: always
    depends_on:
      - db
    volumes:
      - foodgram_static:/backend_static
      - foodgram_media:/app/media

  frontend:
    image: julianastr/foodgram_frontend
    env_file: ../.env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - foodgram_static:/frontend_static
    depends_on:
      - backend
  nginx:
    image: julianastr/foodgram_gateway
    env_file: ../.env
    restart: always
    volumes:
      - foodgram_static:/static/
      - foodgram_media:/app/media/
    ports:
      - 8000:80
    depends_on:
      - backend
