version: '3'

volumes:
  pg_data_production:
  static:
  media:

services:
  db:
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: julianastr/foodgram_backend
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/app/media

  frontend:
    image: julianastr/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - db

  nginx:
    image: julianastr/foodgram_gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    restart: always
    ports:
      - 8000:80
    depends_on:
      - backend
