# Generated by Django 3.2 on 2023-08-14 14:11

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(default=1, validators=[api.validators.validate_time], verbose_name='Время приготовления'),
        ),
    ]
